backend:
  name: github
  repo: indiepaul/iamundefined

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Category", name: "category", widget: "list"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}